import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import GuessProvider from "@/lib/providers/guess_provider";
import MainContainer from "@/components/main_container";
import DialogModal from "@/components/dialog_modal";
import DialogProvider from "@/lib/providers/dialog_provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Navbar />
				<DialogProvider>
					<div className="p-4">
						<MainContainer>
							<GuessProvider>{children}</GuessProvider>
						</MainContainer>
					</div>
					<DialogModal />
				</DialogProvider>
			</body>
		</html>
	);
}
